name: build_arborx_geometric_search
description: Build the geometric search functionality with ArborX
runs:
  using: composite
  steps:
    - name: Build ArborX
      shell: bash
      env:
        kokkos_dir: /opt/4C-dependencies/lib/cmake/Kokkos
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir -p src/build/arborx
        cd src/build/arborx
        cmake -DKokkos_DIR=${{ env.kokkos_dir }} ../../beamme/geometric_search/src -G Ninja
        ninja
