[build-system]
requires = ["setuptools", "numpy", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "MeshPy"
version = "1.0"
authors = [
  {name = "Ivo Steinbrecher", email = "ivo.steinbrecher@unibw.de"},
  {name = "Dao Viet Anh"},
  {name = "Nora Hagmeyer"},
  {name = "Matthias Mayr"},
  {name = "David Rudlstorfer", email = "david.rudlstorfer@tum.de"},
]
description = "MeshPy: A beam finite element input generator"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["Generator", "Beams", "FEM"]
classifiers = ["Programming Language :: Python :: 3.10"]

requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
packages = [
  "meshpy",
  "meshpy.abaqus",
  "meshpy.four_c",
  "meshpy.geometric_search",
  "meshpy.mesh_creation_functions",
  "meshpy_testing",
  "meshpy_tutorial"
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-dir]
meshpy_testing = "tests"
meshpy_tutorial = "tutorial"

[tool.setuptools.package-data]
"meshpy_tutorial" = ["4C_input_solid_tutorial.dat"]

[project.optional-dependencies]
CI-CD = [
  "coverage==7.4.4",
  "coverage-badge",
  "cubitpy@git+https://github.com/imcs-compsim/cubitpy.git@main",
  "setuptools" # Needed for coverage-badge
]
