[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "MeshPy"
description = "MeshPy: A beam finite element input generator"
authors = [
  {name = "Ivo Steinbrecher", email = "ivo.steinbrecher@unibw.de"},
  {name = "MeshPy Authors"}
]
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "autograd",
  "geomdl",
  "ipykernel",
  "notebook",
  "numpy",
  "numpy-quaternion",
  "pyvista",
  "scipy",
  "splinepy",
  "vtk"
]

dynamic = ["version"]

[project.optional-dependencies]
cubitpy = ["cubitpy@git+https://github.com/imcs-compsim/cubitpy.git@main"]
cython = ["cython"]
dev = [
  "coverage-badge",
  "coverage",
  "pdoc",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pyvista_utils@git+https://github.com/isteinbrecher/pyvista_utils.git@main",
  "testbook"
]

[project.scripts]
compile-cython = "meshpy.utils.compile_cython:main"

[project.urls]
Homepage = "https://imcs-compsim.github.io/meshpy/"
Documentation = "https://imcs-compsim.github.io/meshpy/api-documentation/"
Repository = "https://github.com/imcs-compsim/meshpy/"
Issues = "https://github.com/imcs-compsim/meshpy/issues/"


# tools

[tool.coverage.run]
omit = ["src/meshpy/utils/compile_cython.py"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-p pytest_cov --cov-report=term --cov-report=html --cov-fail-under=90 --cov=src/meshpy/"
markers = [
  "fourc: tests in combination with 4C",
  "arborx: tests in combination with ArborX",
  "cubitpy: tests in combination with CubitPy",
  "cython: tests in combination with Cython compiled code",
  "performance: performance tests of MeshPy"
]
