[build-system]
requires = ["setuptools", "Cython", "numpy", "wheel"]


[tool.setuptools]
packages = [
  "meshpy",
  "meshpy.abaqus",
  "meshpy.four_c",
  "meshpy.geometric_search",
  "meshpy.mesh_creation_functions",
  "meshpy.simulation_manager",
  "meshpy_testing",
  "meshpy_tutorial"
]

[tool.setuptools.package-dir]
meshpy_testing = "tests"
meshpy_tutorial = "tutorial"

[tool.setuptools.package-data]
"meshpy.simulation_manager" = ["batch_template.sh"]
"meshpy_tutorial" = ["4C_input_solid_tutorial.dat"]


[project]
name = "MeshPy"
authors = [
  {name = "Ivo Steinbrecher", email = "ivo.steinbrecher@unibw.de"},
]
description = "MeshPy: A beam finite element input generator"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "autograd",
  "black==22.12.0",
  "Cython",
  "geomdl",
  "numpy",
  "pyvista",
  "pyvista_utils@git+https://github.com/isteinbrecher/pyvista_utils.git@86210ab",
  "scipy",
  "vtk"
]
dynamic = ["version"]


[project.optional-dependencies]
CI-CD = [
  "coverage==7.4.4",
  "coverage-badge",
  "setuptools" # Needed for coverage-badge
]
