[build-system]
requires = ["setuptools", "Cython", "numpy", "wheel"]


[tool.setuptools]
packages = [
  "meshpy",
  "meshpy.abaqus",
  "meshpy.cosserat_curve",
  "meshpy.examples",
  "meshpy.four_c",
  "meshpy.geometric_search",
  "meshpy.mesh_creation_functions",
  "meshpy.space_time",
  "meshpy_testing",
  "meshpy_tutorial"
]

[tool.setuptools.package-dir]
meshpy_testing = "tests"
meshpy_tutorial = "tutorial"
"meshpy.examples" = "examples/utils"

[tool.setuptools.package-data]
"meshpy_tutorial" = ["4C_input_solid_tutorial.dat"]


[project]
name = "MeshPy"
authors = [
  {name = "Ivo Steinbrecher", email = "ivo.steinbrecher@unibw.de"},
]
description = "MeshPy: A beam finite element input generator"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "autograd",
  "black==22.12.0",
  "Cython",
  "geomdl",
  "ipykernel",
  "notebook",
  "numpy",
  "numpy-quaternion",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pyvista",
  "pyvista_utils@git+https://github.com/isteinbrecher/pyvista_utils.git@main",
  "scipy",
  "splinepy",
  "vtk"
]
dynamic = ["version"]


[project.optional-dependencies]
CI-CD = [
  "coverage==7.4.4",
  "coverage-badge",
  "cubitpy@git+https://github.com/imcs-compsim/cubitpy.git@main",
  "setuptools", # Needed for coverage-badge
  "testbook"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-p pytest_cov --cov-report=term --cov-report=html --cov-fail-under=90 --cov=meshpy/ --cov=tutorial/ --cov-append"
markers = [
  "fourc: tests in combination with 4C",
  "arborx: tests in combination with ArborX",
  "cubitpy: tests in combination with CubitPy",
  "performance: performance tests of MeshPy"
]
