name: run_performance_tests
description: MeshPy performance test suite
runs:
  using: composite
  steps:
    - name: MeshPy testing
      shell: bash
      env:
        CUBIT_ROOT: /imcs/public/compsim/opt/cubit-15.2
        PERFORMANCE_TESTING_HOST: github-sisyphos-docker
      run: |
        cd ${GITHUB_WORKSPACE}
        source python-testing-environment/bin/activate
        pip install .[CI-CD]
        python --version
        pip list
        cd tests
        python performance_testing.py
