name: setup_virtual_python_environment
description: Configure the python virtual environment
runs:
  using: composite
  steps:
    - name: Setup virtual environment
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        python -m venv python-workflow-venv
        source python-workflow-venv/bin/activate
        pip install --upgrade pip
