name: run_tests
description: Perform Test suite
inputs:
  install-command:
    description: Command to install BeamMe with pip
    required: false
    default: ".[dev,fourc]"
  source-command:
    description: Command to source the virtual environment
    required: false
    default: ""
  additional-pytest-flags:
    description: Additional flags to pass to pytest, i.e., markers
    required: false
    default: ""
  cubit-root:
    description: Path to the cubit installation
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Testing
      shell: bash
      env:
        BEAMME_FOUR_C_EXE: /home/user/4C/build/4C
        OMPI_MCA_rmaps_base_oversubscribe: 1
      run: |
        export CUBIT_ROOT=${{ inputs.cubit-root }}
        cd ${GITHUB_WORKSPACE}
        ${{ inputs.source-command }}
        pip install ${{ inputs.install-command }}
        python --version
        pip list
        TEMP_DIR="${RUNNER_TEMP}/beamme_pytest"
        mkdir -p "$TEMP_DIR"
        echo "PYTEST_TMPDIR=$TEMP_DIR" >> $GITHUB_ENV
        pytest  --basetemp="$TEMP_DIR" ${{ inputs.additional-pytest-flags}} --color=yes
