name: run_tests
description: Perform MeshPy test suite
inputs:
  install-command:
    description: Command to install MeshPy with pip
    required: false
    default: ".[dev,fourc]"
  source-command:
    description: Command to source the virtual environment
    required: false
    default: ""
  additional-pytest-flags:
    description: Additional flags to pass to pytest, i.e., markers
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: MeshPy testing
      shell: bash
      env:
        MESHPY_FOUR_C_EXE: /home/user/4C/build/4C
        CUBIT_ROOT: /imcs/public/compsim/opt/cubit-15.2
        OMPI_MCA_rmaps_base_oversubscribe: 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ${{ inputs.source-command }}
        pip install ${{ inputs.install-command }}
        python --version
        pip list
        TEMP_DIR="${RUNNER_TEMP}/meshpy_pytest"
        mkdir -p "$TEMP_DIR"
        echo "PYTEST_TMPDIR=$TEMP_DIR" >> $GITHUB_ENV
        pytest  --basetemp="$TEMP_DIR" ${{ inputs.additional-pytest-flags}} --color=yes
