name: setup_cubit
description: Setup a Cubit installation for testing
inputs:
  cubit_download_url:
    description: URL where Cubit can be downloaded from
    required: true
runs:
  using: composite
  steps:
    - name: Download and unpack Cubit
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        wget -q ${{ inputs.cubit_download_url }}
        tar -xzf *.tar.gz
