name: Code quality

on:
  schedule:
    - cron: '0 06 * * *'
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    type: choice

jobs:
  code-check:
    name: Code check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup virtual python environment
        uses: ./.github/actions/setup_virtual_python_environment
      - name: Code quality checks
        uses: ./.github/actions/code_check
