name: Build documentation

on:
  # Only build the documentation once the test suite has completed on the main branch (only after merged PR's)
  workflow_run:
    workflows: [Test suite]
    types: [completed]
    branches: [main]

jobs:
  build_documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup virtual python environment
        uses: ./.github/actions/setup_virtual_python_environment
      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}
          source python-workflow-venv/bin/activate
          pip install -e .[dev]
      - name: Build API documentation
        run: |
          source python-workflow-venv/bin/activate
          pdoc --math --docformat google --output-dir api-documentation src/meshpy/
      - name: Upload API documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: api-documentation/
